routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//---------------------------------------------------------------Property Routes
Route::resource('property', 'PropertyController');
Route::resource('propertyproject','PropertyProjectController');
Route::resource('propertytransactions','PropertyTransactionController');
Route::resource('propertyfiles', 'PropertyFileController');

Route::get('/propertytransactions/create/{id}', 'PropertyTransactionController@create')->name('propertytransactions.create');
Route::resource('propertyexpenses','PropertyExpenseController');
Route::get('/propertyexpenses/create/{id}', 'PropertyExpenseController@create')->name('propertyexpenses.create');
Route::post('/propertyfiles/sale/{id}', 'PropertyFileController@create')->name('propertyfiles.sale');
//Lenders Routes
Route::resource('lenders','LendersController');
//Office Banks and Bank Transaction Routes
Route::resource('banks','OfficeBanksController');
Route::resource('bank_transaction','BankTransactionsController');
//Route::get('/transactions','BankTransactionsController@bankTransactionsDatewise')->name('transactionsdatewise');
//Route::view('/welcome', 'pdashboard');
//----------------------------------------------------------------Emplooyees Routes
Route::resource('payslips', 'EmpSalarySlipsController');	
Route::resource('employees', 'EmployeesController');
Route::resource('advsalarys', 'AdvsalarysrecsController');

//Files Route
Route::get('/file/profit', 'FilesController@profit');
Route::get('/file/sale', 'FilesController@sale');
Route::get('/file/createfilesale/{id}', 'FilesController@createfilesale');
Route::get('/file/showfilesale/{id}', 'FilesController@showfilesale')->name('file.showfilesale');
Route::get('/file/editfilesale/{id}', 'FilesController@editfilesale');
Route::post('/file/updatefilesale/{id}', 'FilesController@updatefilesale');
Route::post('/file/filesale/{id}', 'FilesController@filesale');
//related to file purchase
Route::resource('file', 'FilesController');
//related to file transaction
Route::resource('filetransaction','FilePurchaseTransactionController');
//passing parameter to file transaction create method in controller
Route::get('filetransaction/create/{id}', 'FilePurchaseTransactionController@create')->name('filetransaction.create');
//file sale trnasaction
Route::resource('filesaletransaction','FileSaleTransactionController');
//passing parameter to file transaction create method in controller
Route::get('filesaletransaction/create/{id}', 'FileSaleTransactionController@create')->name('filesaletransaction.create');
//file purchase history when click on 'view purchase history' button
Route::get('/file/showfilehistory/{id}', 'FilesController@showfilehistory');
//for print
Route::get('/file/printfilehistory/{id}', 'FilesController@print');

//for office expenditure
Route::resource('officeexpenditure', 'OfficeExpenditureController');
Route::get('/deposit', 'OfficeExpenditureController@deposit')->name('officeexpenditure');
Route::post('/addofficedeposit', 'OfficeExpenditureController@addofficedeposit');
Route::post('/deleteofficedeposit/{id}', 'OfficeExpenditureController@deleteofficedeposit');
Route::get('/monthlyreport', 'OfficeExpenditureController@monthlyreport');
Route::post('/checkmonthlyexpenses', 'OfficeExpenditureController@checkmonthlyexpenses');
Route::post('/checkmonthlydeposit', 'OfficeExpenditureController@checkmonthlydeposit');

resources/views/advsalarys/create.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Kashaf-Enterprises</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">		   						
					<div class="card">
						<div class="card-header">
							<div class="card-title">Add Advance Salary</div></div>
							<div class="card-body">
								<form id="formvalidation" method="post" action="{{ route('advsalarys.store') }}">
									<input type="hidden" name="_token" value="{{ csrf_token() }}">
									<input type="hidden" id="rem_balance" name="balance" >
									<div class="row">
										<div class="form-group col-md-4">
											<label for="Employee Select">Select Employee</label>
											<select class="form-control input-solid" name="emp_id" >
												<option value="">Select</option>
												@foreach($emp as $e)
												<option value="{{ $e->id }}">{{ $e->name }}</option>
												@endforeach
											</select>
										</div>	
									</div>
									<div class="row">
										<div class="form-group col-md-4">
											<label for="Loan Amount">Loan Amount</label>
											<input type="text" class="validate[required, custom[onlyNumberSp],minSize[1]] form-control" id="advance_payment" name="loan_amount" placeholder="Amount" autocomplete="off">
										</div>
										<div class="form-group col-md-4">
											<label for="month">Month</label>			
											<input type="date" class="validate[required] form-control" name="loan_month" >
										</div>	
									</div>
									<div class="row">
										<div class="form-group col-md-4">
											<label for="Total Installments">Total Installments</label>	
											<input type="text" class="validate[required, custom[onlyNumberSp],minSize[1]] form-control" name="total_installments" placeholder="Installments" autocomplete="off">
										</div>
										<div class="form-group col-md-4">
											<label for="phone_no">Installment per Month</label>
											<input type="text" class="validate[required, custom[onlyNumberSp],minSize[1]] form-control" name="monthly_installment" placeholder="Installment Per Month" autocomplete="off">
										</div>	
									</div>					
									<div class="card-action row justify-content-md-center">
										<div class="col-md-auto">
										<button class="btn btn-primary" value="Save">Submit</button>
										<button type="Reset" class="btn btn-danger" value="Reset">Reset</button>
										</div>
									</div>
								</form>
							</div>
						</div>		
					</div>
				</div>
				@include('partials.footer')
			</div>
			@include ('partials.js-libraries')
		</div>
	</body>
	</html>

resources/views/advsalarys/edit.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Kashaf-Enterprises</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">		   						
					<div class="card">
						<div class="card-header">
							<div class="card-title">Update Advance Salary Details</div></div>
							<div class="card-body">
								<form method="post" action="{{ route('advsalarys.update',$advrecords->id) }}">
									@method('PUT')
									<input type="hidden" name="_token" value="{{ csrf_token() }}">
									<input type="hidden" id="rem_balance" name="balance" >
									<div class="row">
										<div class="form-group col-md-4">
											<label for="Loan Amount">Loan Amount</label>
<<<<<<< .merge_file_a11820
											<input type="text" class="form-control" id="advance_payment" name="loan_amount" value="{{ $advrecords->loan_amount }}" placeholder="Amount"required="" autocomplete="off">
=======
											<input type="text" class="form-control" id="advance_payment" name="loan_amount" value="{{ $advrecords->loan_amount }}" required="" autocomplete="off">
>>>>>>> .merge_file_a01472
										</div>
										<div class="form-group col-md-4">
											<label for="cnic">Month</label>								
											<input type="date" class="form-control" name="loan_month" value="{{ $advrecords->loan_month }}" required="" autocomplete="off">
										</div>	
									</div>
									<div class="row">
										<div class="form-group col-md-4">
											<label for="Total Installments">Total Installments</label>	
											<input type="text" class="form-control" name="total_installments" value="{{ $advrecords->total_installments }}" placeholder="Installments"required="" autocomplete="off">
										</div>
										<div class="form-group col-md-4">
											<label for="phone_no">Installment per Month</label>
											<input type="text" class="form-control" name="monthly_installment" value="{{ $advrecords->monthly_installment }}" placeholder="Installment Per Month"required="" autocomplete="off">
										</div>	
									</div>					
									<div class="card-action row justify-content-md-center">
										<div class="col-md-auto">
										<button class="btn btn-primary" value="Save">Update</button>
										</div>
									</div>
								</form>
							</div>
						</div>		
					</div>
				</div>
				@include('partials.footer')
			</div>
			@include ('partials.js-libraries')
		</div>
	</body>
	</html>

resources/views/advsalarys/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Kashaf-Enterprises</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">
					<h4 class="page-title">List of Employess with Advance Salary</h4>
					<div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">Select <b>Employee</b> or <b>Month</b> for Which You Want to See the Advance Detail</div>
                                </div>
                                <div class="card-body">
                                    <form id="formvalidation" method="GET" action="{{ route('advsalarys.index') }}">  
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <div class="row">
                                        	<div class="form-group col-md-4">
                                                <label for="Employee Select">Select Employees</label>
                                                <select  name="id" class="form-control input-solid" >
                                                    <option value="">Select Employee</option>
                                                    @foreach($employees as $emp)
                                                    	@foreach($advrecords as $adv)
                                                    		@if($emp->id == $adv->emp_id)
                                                    		<option value="{{ $emp->id }}">{{ $emp->name }}</option>
                                                    		@endif
                                                    	@endforeach
                                                    @endforeach
                                                </select>
                                            </div>
                                            <div class="form-group col-md-3">
                                                <label for="Account Select">Select Month</label>
                                                <input type="month" class="form-control" name="month">
                                            </div>
                                        </div>
                                        <div class="card-action row justify-content-md-center"">
                                            <div class="col-md-auto">
                                                <input type="Submit" class="btn btn-warning" value="Submit">
                                                <input type="reset" class="btn btn-danger" value="Cancel">
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
					<div class="card">
						<div class="card-header">
							<div class="row">
								<div class="form-group col-md-3">
									<a href="{{ route('advsalarys.create') }}" class="btn btn-primary  text-left mt-3 mb-3"><i class="la la-plus"></i> Add Addvance Salary</a>
								</div>
								<div class="form-group col-md-3">
									<a href="{{ url('advsalarys/view') }}" class="btn btn-success  text-left mt-3 mb-3"><i class="la la-eye"></i> View Employees List</a>
								</div>
								@if(!empty($month))
								<div class="form-group col-md-auto" style="margin-top: 15px;">
									<input type="text" class="btn btn-info" value="Month = {{ date('M Y', strtotime($month)) }} " readonly="">
								</div>
								@endif
								@if(!empty($id))
								<div class="form-group col-md-auto" style="margin-top: 15px;">
									<input type="text" class="btn btn-info" value="Rem Installments = {{ $rem_installments }} " readonly="">
								</div>
								@endif
							</div>
						</div>
							<div class="card-body">
								<table class="table table-striped mt-3 datatablejs">
									<thead>
										<tr>
											<th scope="col">S.No</th>
											<th scope="col">Name</th>
											<th scope="col">Loan Amount</th>	
											<th scope="col">Monthly Installment</th>
											<th scope="col">Installment Month</th>
											<th scope="col">Rem Loan Balance</th>
											@if(empty($month) && $loan_balance == 0)
											<th scope="col">Alert</th>
											@endif
										</tr>
									</thead>
									<tbody>
										@if(!empty($slips))
											@foreach($slips as $slip)
												<tr>
													<td>{{$loop->iteration}}</td>
													<td>
														{{ $slip->name }}
													</td>
													<td>
														@foreach($advrecords as $adv)
														@if($slip->emp_id == $adv->emp_id)
														{{ $adv->loan_amount }}
														@endif
														@endforeach
													</td>
													<td>
														@foreach($advrecords as $adv)
														@if($slip->emp_id == $adv->emp_id)
														{{ $adv->monthly_installment }}
														@endif
														@endforeach
													</td>
													<td>{{ date('M Y', strtotime($slip->salary_month)) }}</td>
													<td>
														<button class="btn btn-danger btn-sm">Rs. {{ $slip->rem_loan_balance }}</button>
													</td>
													@if(empty($month) && $loan_balance == 0)
													<td>
														<button class="btn btn-success btn-sm">Loan Completed</button>
													</td>
													@endif
													</tr>
											@endforeach
										@endif
									</tbody>
								</table>					
							</div>
						</div>
					</div>
				</div>
				@include('partials.footer')
			</div>
			@include ('partials.js-libraries')
		</div>
	</body>
	</html>

resources/views/advsalarys/show.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Kashaf-Enterprises</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">
					<h4 class="page-title">List of Employess with Advance Salary</h4>
					<div class="row">
                        <div class="col-md-12">
                            <div class="card">
                                <div class="card-header">
                                    <div class="card-title">Employees</div>
                                </div>
                                <div class="card-body">
								<table class="table table-striped mt-3 datatablejs">
									<thead>
										<tr>
											<th scope="col">S.No</th>
											<th scope="col">Name</th>
											<th scope="col">Loan Month</th>
											<th scope="col">Loan Amount</th>
											<th scope="col">Total Installments</th>	
											<th scope="col">Monthly Installment</th>
											<th scope="col">Actions</th>
										</tr>
									</thead>
									<tbody>
										@foreach($advrecords as $adv)
										<tr>
											<td>{{$loop->iteration}}</td>
											<td>
												@foreach($employees as $emp)
												@if($adv->emp_id == $emp->id)
												{{ $emp->name }}
												@endif
												@endforeach
											</td>
											<td>{{ date('d M Y', strtotime($adv->loan_month)) }}</td>
											<td>{{ $adv->loan_amount }}</td>
											<td>{{ $adv->total_installments }}</td>
											<td>{{ $adv->monthly_installment }}</td>
											<td>
												<a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-danger btn-xs">Delete</a>
												<form onsubmit="return confirm('Do you really want to delete?');" action="{{ route('advsalarys.destroy',$adv->id) }}" method="post">
												@method('DELETE')
												<input type="hidden" name="_token" value="{{ csrf_token() }}">
												</form>
											</td>
										</tr>
										@endforeach
									</tbody>
								</table>					
							</div>
                            </div>
                        </div>
                    </div>
					</div>
				</div>
				@include('partials.footer')
			</div>
			@include ('partials.js-libraries')
		</div>
	</body>
	</html>