routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//---------------------------------------------------------------Property Routes
Route::resource('property', 'PropertyController');
Route::resource('propertyproject','PropertyProjectController');
Route::resource('propertytransactions','PropertyTransactionController');
Route::resource('propertyfiles', 'PropertyFileController');

Route::get('/propertytransactions/create/{id}', 'PropertyTransactionController@create')->name('propertytransactions.create');
Route::resource('propertyexpenses','PropertyExpenseController');
Route::get('/propertyexpenses/create/{id}', 'PropertyExpenseController@create')->name('propertyexpenses.create');
Route::post('/propertyfiles/sale/{id}', 'PropertyFileController@create')->name('propertyfiles.sale');
//Lenders Routes
Route::resource('lenders','LendersController');
//Office Banks and Bank Transaction Routes
Route::resource('banks','OfficeBanksController');
Route::resource('bank_transaction','BankTransactionsController');
//Route::get('/transactions','BankTransactionsController@bankTransactionsDatewise')->name('transactionsdatewise');
//Route::view('/welcome', 'pdashboard');
//----------------------------------------------------------------Emplooyees Routes
Route::resource('payslips', 'EmpSalarySlipsController');	
Route::resource('employees', 'EmployeesController');
Route::resource('advsalarys', 'AdvsalarysrecsController');

//Files Route
Route::get('/file/profit', 'FilesController@profit');
Route::get('/file/sale', 'FilesController@sale');
Route::get('/file/createfilesale/{id}', 'FilesController@createfilesale');
Route::get('/file/showfilesale/{id}', 'FilesController@showfilesale')->name('file.showfilesale');
Route::get('/file/editfilesale/{id}', 'FilesController@editfilesale');
Route::post('/file/updatefilesale/{id}', 'FilesController@updatefilesale');
Route::post('/file/filesale/{id}', 'FilesController@filesale');
//related to file purchase
Route::resource('file', 'FilesController');
//related to file transaction
Route::resource('filetransaction','FilePurchaseTransactionController');
//passing parameter to file transaction create method in controller
Route::get('filetransaction/create/{id}', 'FilePurchaseTransactionController@create')->name('filetransaction.create');
//file sale trnasaction
Route::resource('filesaletransaction','FileSaleTransactionController');
//passing parameter to file transaction create method in controller
Route::get('filesaletransaction/create/{id}', 'FileSaleTransactionController@create')->name('filesaletransaction.create');
//file purchase history when click on 'view purchase history' button
Route::get('/file/showfilehistory/{id}', 'FilesController@showfilehistory');
//for print
Route::get('/file/printfilehistory/{id}', 'FilesController@print');

//for office expenditure
Route::resource('officeexpenditure', 'OfficeExpenditureController');
Route::get('/deposit', 'OfficeExpenditureController@deposit')->name('officeexpenditure');
Route::post('/addofficedeposit', 'OfficeExpenditureController@addofficedeposit');
Route::post('/deleteofficedeposit/{id}', 'OfficeExpenditureController@deleteofficedeposit');
Route::get('/monthlyreport', 'OfficeExpenditureController@monthlyreport');
Route::post('/checkmonthlyexpenses', 'OfficeExpenditureController@checkmonthlyexpenses');
Route::post('/checkmonthlydeposit', 'OfficeExpenditureController@checkmonthlydeposit');

app/Property.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Property extends Model
{
	public $table = 'propertys';
    protected $guarded = [];
    
    public function propertyproject(){
    	return $this->belongsTo('App\PropertyProject');
    }

    public function propertytransaction(){
    	return $this->belongsTo('App\PropertyTransaction');
    }

    public function propertyexpense(){
    	return $this->belongsTo('App\PropertyExpense');
    }

    public function lender(){
        return $this->belongsTo('App\Lender');
    }

    public function PropertyFile(){
        return $this->belongsTo('App\PropertyFile');    
    }
}

app/PropertyProject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PropertyProject extends Model
{
    public $table = 'propertyprojects';
}

app/Http/Controllers/PropertyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth; 
use App\Property;
use App\PropertyProject;
use App\PropertyTransaction;
use App\PropertyExpense;
use App\Lender;
use App\PropertyFile;
use Session;

class PropertyController extends Controller
{

    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $arr['propertys'] = Property::all(); 
        return view('property.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $propertyprojects = PropertyProject::all();
        return view('property.create', compact('propertyprojects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Property $property)
    {
        $property->propertyproject_id =$request->propertyproject_id;
        $property->owner_name         =$request->owner_name;
        $property->mouza              =$request->mouza;
        $property->acr                =$request->acr;
        $property->kanal              =$request->kanal;
        $property->marla              =$request->marla;
        $property->yard               =$request->yard;
        $property->total_marlas       =$request->total_marlas;
        $property->rate_per_acr       =$request->rate_per_acr;
        $property->rate_per_marla     =$request->rate_per_marla;
        $property->total_amount       =$request->total_amount;
        $property->point_entry        =$request->point_entry;
        $property->exemption_rate     =$request->exemption_rate;
        $property->no_of_files        =$request->no_of_files;
        $property->proprety_commission=$request->proprety_commission;
        $property->purchasing_date    =$request->purchasing_date;
        $property->save();

        Session::flash('success', 'Property record was successfully saved!');
        
        $data = [
            $property->id,
            $property->owner_name,
            $property->total_amount
        ];
        $balance_amount = null;
        $lenders = lender::all();
        return view('property.property_transactions.create', compact('data', 'lenders', 'balance_amount'))->with('message', 'Property record has been added successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $property = Property::find($id);
        $propertyprojects = PropertyProject::all();
        $propertytransactions = PropertyTransaction::where('property_id',$id)->get();
        $lenders = Lender::all();
        $propertyexpenses = PropertyExpense::where('property_id', $id)->sum('expenses_amount');

        $total_property_price = $property['total_amount'] + $propertyexpenses + $property['proprety_commission'];

        $average_file_price= round($total_property_price / $property['no_of_files'], 2);

        $propertyfiles = PropertyFile::orderBy('id','DESC')->where('property_id','=',$id)->get();
        
        $remaining_files = PropertyFile::orderBy('id','DESC')->where('property_id','=',$id)->get()->pluck('remaining_files')->first();
        $total_profit = PropertyFile::select('file_profit')->sum('file_profit');
        

        return view('property.show', compact('property','propertyprojects', 'propertytransactions', 'lenders', 'propertyexpenses', 'total_property_price', 'average_file_price', 'propertyfiles', 'remaining_files','total_profit'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Property $property)
    {
        $propertyprojects = PropertyProject::all();
        return view('property.edit',compact('property','propertyprojects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Property $property)
    {
        $property->propertyproject_id=$request->propertyproject_id;
        $property->owner_name        =$request->owner_name;
        $property->mouza             =$request->mouza;
        $property->acr               =$request->acr;
        $property->kanal             =$request->kanal;
        $property->marla             =$request->marla;
        $property->yard              =$request->yard;
        $property->total_marlas      =$request->total_marlas;
        $property->rate_per_acr      =$request->rate_per_acr;
        $property->rate_per_marla    =$request->rate_per_marla;
        $property->total_amount      =$request->total_amount;
        $property->point_entry       =$request->point_entry;
        $property->exemption_rate    =$request->exemption_rate;
        $property->no_of_files       =$request->no_of_files;
        $property->proprety_commission=$request->proprety_commission;
        $property->purchasing_date    =$request->purchasing_date;
        $property->save();

        Session::flash('success', 'Property record was successfully updated!');

        return redirect()->route('property.show', $property->id );

        //return back()->withInfo('Property record has been updated successfully');
        //return redirect()->route('property', [$property]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
       Property::destroy($id);
       return redirect()->route('property.index');
    }

    public function delete_sold_file($id)
    {
       PropertyFile::destroy($id);
       return redirect()->back(); }


}

app/Http/Controllers/PropertyProjectController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\PropertyProject;
use Session;

class PropertyProjectController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $propertyProjects = PropertyProject::all();
        return view('property.property_project.propertyprojects', compact('propertyProjects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('property.property_project.propertyprojects');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, PropertyProject $propertyproject)
    {
       $propertyproject->project_name = $request->project_name;
       $propertyproject->project_city = $request->project_city;
       $propertyproject->save();

        Session::flash('success', 'Property Project was successfully saved!');
       
       return back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $propertyproject = PropertyProject::find($id);
        $totalpropertyprojects = PropertyProject::all();
        
        return view('property.property_project.edit', compact('propertyproject', 'totalpropertyprojects'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PropertyProject $propertyproject)
    {
       $propertyproject->project_name = $request->project_name;
       $propertyproject->project_city = $request->project_city;
       $propertyproject->save();

        Session::flash('success', 'Property Project was successfully updated!');

        $propertyProjects = PropertyProject::all();
        return view('property.property_project.propertyprojects', compact('propertyProjects'));

        //return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Propertyproject::destroy($id);
        Session::flash('info', 'Property Project was successfully deleted!');
        
        $propertyProjects = PropertyProject::all();
        return view('property.property_project.propertyprojects', compact('propertyProjects'));
        //return redirect()->route('propertyproject.propertyprojects');
    }
}

resources/views/property/property_project/edit.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>{{ config('app.name', 'Laravel') }}</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">		   						
					<h4 class="page-title">Property Projects</h4>
					@include('partials.flash-message')
						<div class="row">

							<div class="col-md-6">
								<div class="card">
									<div class="card-header">
										<div class="card-title">Projects List</div>
									</div>
									<div class="card-body">
										<table class="table table-striped mt-3 datatablejs">
											<thead>
												<tr>
													<th scope="col">S.No</th>
													<th scope="col">Project Name</th>
													<th scope="col">Action</th>
												</tr>
											</thead>
											<tbody>
												@foreach($totalpropertyprojects as $tpropertyproject)
												<tr>
													<td>{{$loop->iteration}}</td>
													<td>{{$tpropertyproject->project_name}} {{$tpropertyproject->project_city}}</td>
													<td>
														<a href="{{ route('propertyproject.edit',$tpropertyproject->id) }}" class="btn btn-info btn-xs">Edit</a>
														<a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-danger btn-xs">Delete</a>
														<form onsubmit="return confirm('Do you really want to delete?');" action="{{ route('propertyproject.destroy',$tpropertyproject->id) }}" method="post">
															@method('DELETE')
															<input type="hidden" name="_token" value="{{ csrf_token() }}">
														</form>
													</td>
												</tr>
												@endforeach
											</tbody>
										</table>
									</div>
								</div>
							</div>

							<div class="col-md-6">
								<div class="card">
									<div class="card-header">
										<div class="card-title">Edit Project</div>
									</div>
									<div class="card-body">
										<form id="formvalidation" method="post" action="{{ route('propertyproject.update', $propertyproject->id) }}">
											@method('PUT')
											<input type="hidden" name="_token" value="{{ csrf_token() }}">
											<div class="row">
												<div class="form-group col-md-6">
													<label for="Project Name">Project Name</label>
													<input type="textbox" class="validate[required,custom[onlyLetterSp],minSize[3]] form-control" name="project_name" value="{{$propertyproject->project_name}}" placeholder="Enter Project Name">
												</div>
												<div class="form-group col-md-6">
													<label for="Select City">Select City</label>
													<select class="form-control" name="project_city">
														<option value="{{$propertyproject->project_city}}">{{$propertyproject->project_city}}</option>
														<option value="Islamabad">Islamabad</option>
														<option value="Lahore">Lahore</option>
														<option value="Karachi">Karachi</option>
														<option value="Rawalpindi">Rawalpindi</option>
														<option value="Abbottabad">Abbottabad</option>
														<option value="Alipur">Alipur</option>
														<option value="Arifwala">Arifwala</option>
														<option value="Attock">Attock</option>
														<option value="Badin">Badin</option>
														<option value="Bahawalnagar">Bahawalnagar</option>
														<option value="Bahawalpur">Bahawalpur</option>
														<option value="Bannu">Bannu</option>
														<option value="Battagram">Battagram</option>
														<option value="Bhimber">Bhimber</option>
														<option value="Burewala">Burewala</option>
														<option value="Chakwal">Chakwal</option>
														<option value="Chaman">Chaman</option>
														<option value="Chichawatni">Chichawatni</option>
														<option value="Chiniot">Chiniot</option>
														<option value="Chishtian">Chishtian</option>
														<option value="Chitral">Chitral</option>
														<option value="Dera Ismail Khan">Dera Ismail Khan</option>
														<option value="Dera Ghazi Khan">Dera Ghazi Khan</option>
														<option value="Faisalabad">Faisalabad</option>
														<option value="Gilgit">Gilgit</option>
														<option value="Gujar Khan">Gujar Khan</option>
														<option value="Gujranwala">Gujranwala</option>
														<option value="Gujrat">Gujrat</option>
														<option value="Gwadar">Gwadar</option>
														<option value="Haripur">Haripur</option>
														<option value="Hasilpur">Hasilpur</option>
														<option value="Hunza / Nagar">Hunza / Nagar</option>
														<option value="Hyderabad">Hyderabad</option>
														<option value="Harrapa">Harrapa</option>
														<option value="Jacobabad">Jacobabad</option>
														<option value="Jahanian">Jahanian</option>
														<option value="Jaranwala">Jaranwala</option>
														<option value="Jhang">Jhang</option>
														<option value="Jhelum">Jhelum</option>
														<option value="Kasur">Kasur</option>
														<option value="Khairpur">Khairpur</option>
														<option value="Khanewal">Khanewal</option>
														<option value="Khanpur">Khanpur</option>
														<option value="Kharian">Kharian</option>
														<option value="Khushab">Khushab</option>
														<option value="Khuzdar">Khuzdar</option>
														<option value="Kohat">Kohat</option>
														<option value="Kohistan">Kohistan</option>
														<option value="Kot Addu">Kot Addu</option>
														<option value="Kotli">Kotli</option>
														<option value="Larkana">Larkana</option>
														<option value="Layyah">Layyah</option>
														<option value="Mailsi">Mailsi</option>
														<option value="Mansehra">Mansehra</option>
														<option value="Mardan">Mardan</option>
														<option value="Mianwali">Mianwali</option>
														<option value="Mirpur">Mirpur</option>
														<option value="Mohenjo-Daro">Mohenjo-Daro</option>
														<option value="Multan">Multan</option>
														<option value="Muridke">Muridke</option>
														<option value="Murree">Murree</option>
														<option value="Muzafargarh">Muzafargarh</option>
														<option value="Muzaffarabad">Muzaffarabad</option>
														<option value="Nawabshah">Nawabshah</option>
														<option value="Nowshera">Nowshera</option>
														<option value="Okara">Okara</option>
														<option value="Peshawar">Peshawar</option>
														<option value="Pakpattan">Pakpattan</option>
														<option value="Quetta">Quetta</option>
														<option value="Rahim Yar Khan">Rahim Yar Khan</option>
														<option value="Rawalakot">Rawalakot</option>
														<option value="Rajanpur">Rajanpur</option>
														<option value="Sadiqabad">Sadiqabad</option>
														<option value="Sahiwal">Sahiwal</option>
														<option value="Sargodha">Sargodha</option>
														<option value="Sawabi">Sawabi</option>
														<option value="Shakargarh">Shakargarh</option>
														<option value="Sheikhupura">Sheikhupura</option>
														<option value="Sialkot">Sialkot</option>
														<option value="Skardu">Skardu</option>
														<option value="Sukkur">Sukkur</option>
														<option value="Swat">Swat</option>
														<option value="Taxila">Taxila</option>
														<option value="Thatta">Thatta</option>
														<option value="Tibba Sultan Pur">Tibba Sultan Pur</option>
														<option value="Toba Tek Singh">Toba Tek Singh</option>
														<option value="Tunsa">Tunsa</option>
														<option value="Vehari">Vehari</option>
														<option value="Wah">Wah</option>
														<option value="Wazirabad">Wazirabad</option>
														<option value="Ziarat">Ziarat</option>
													</select>
												</div>
											</div>
											<div class="row">
												<div class="card-action">
													<input type="Submit" name="" class="btn btn-success" value="Update">
													
													<input type="reset" class="btn btn-danger" value="reset">
												</div>
											</div>
										</form>
									</div>
									
								</div>
							</div>
						
							
						</div>
				</div>
			</div>
			@include('partials.footer')
		</div>
		@include ('partials.js-libraries')
	</div>
</body>
</html>

resources/views/property/property_project/propertyprojects.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>{{ config('app.name', 'Laravel') }}</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">		   						
					<h4 class="page-title">Property Projects</h4>
					@include('partials.flash-message')
						<div class="row">

							<div class="col-md-6">
								<div class="card">
									<div class="card-header">
										<div class="card-title">Add Project</div>
									</div>
									<div class="card-body">
										<form id="formvalidation" method="post" action="{{ route('propertyproject.store') }}">
											<input type="hidden" name="_token" value="{{ csrf_token() }}">
											<div class="row">
												<div class="form-group col-md-6">
													<label for="Project Name">Project Name</label>
													<input type="textbox" class="validate[required,custom[onlyLetterSp],minSize[3]] form-control" name="project_name" placeholder="Enter Project Name">
												</div>
												<div class="form-group col-md-6">
													<label for="Select City">Select City</label>
													<select class="form-control validate[required]" name="project_city">
														<option value="">Choose City</option>
														<option value="Islamabad">Islamabad</option>
														<option value="Lahore">Lahore</option>
														<option value="Karachi">Karachi</option>
														<option value="Rawalpindi">Rawalpindi</option>
														<option value="Abbottabad">Abbottabad</option>
														<option value="Alipur">Alipur</option>
														<option value="Arifwala">Arifwala</option>
														<option value="Attock">Attock</option>
														<option value="Badin">Badin</option>
														<option value="Bahawalnagar">Bahawalnagar</option>
														<option value="Bahawalpur">Bahawalpur</option>
														<option value="Bannu">Bannu</option>
														<option value="Battagram">Battagram</option>
														<option value="Bhimber">Bhimber</option>
														<option value="Burewala">Burewala</option>
														<option value="Chakwal">Chakwal</option>
														<option value="Chaman">Chaman</option>
														<option value="Chichawatni">Chichawatni</option>
														<option value="Chiniot">Chiniot</option>
														<option value="Chishtian">Chishtian</option>
														<option value="Chitral">Chitral</option>
														<option value="Dera Ismail Khan">Dera Ismail Khan</option>
														<option value="Dera Ghazi Khan">Dera Ghazi Khan</option>
														<option value="Faisalabad">Faisalabad</option>
														<option value="Gilgit">Gilgit</option>
														<option value="Gujar Khan">Gujar Khan</option>
														<option value="Gujranwala">Gujranwala</option>
														<option value="Gujrat">Gujrat</option>
														<option value="Gwadar">Gwadar</option>
														<option value="Haripur">Haripur</option>
														<option value="Hasilpur">Hasilpur</option>
														<option value="Hunza / Nagar">Hunza / Nagar</option>
														<option value="Hyderabad">Hyderabad</option>
														<option value="Harrapa">Harrapa</option>
														<option value="Jacobabad">Jacobabad</option>
														<option value="Jahanian">Jahanian</option>
														<option value="Jaranwala">Jaranwala</option>
														<option value="Jhang">Jhang</option>
														<option value="Jhelum">Jhelum</option>
														<option value="Kasur">Kasur</option>
														<option value="Khairpur">Khairpur</option>
														<option value="Khanewal">Khanewal</option>
														<option value="Khanpur">Khanpur</option>
														<option value="Kharian">Kharian</option>
														<option value="Khushab">Khushab</option>
														<option value="Khuzdar">Khuzdar</option>
														<option value="Kohat">Kohat</option>
														<option value="Kohistan">Kohistan</option>
														<option value="Kot Addu">Kot Addu</option>
														<option value="Kotli">Kotli</option>
														<option value="Larkana">Larkana</option>
														<option value="Layyah">Layyah</option>
														<option value="Mailsi">Mailsi</option>
														<option value="Mansehra">Mansehra</option>
														<option value="Mardan">Mardan</option>
														<option value="Mianwali">Mianwali</option>
														<option value="Mirpur">Mirpur</option>
														<option value="Mohenjo-Daro">Mohenjo-Daro</option>
														<option value="Multan">Multan</option>
														<option value="Muridke">Muridke</option>
														<option value="Murree">Murree</option>
														<option value="Muzafargarh">Muzafargarh</option>
														<option value="Muzaffarabad">Muzaffarabad</option>
														<option value="Nawabshah">Nawabshah</option>
														<option value="Nowshera">Nowshera</option>
														<option value="Okara">Okara</option>
														<option value="Peshawar">Peshawar</option>
														<option value="Pakpattan">Pakpattan</option>
														<option value="Quetta">Quetta</option>
														<option value="Rahim Yar Khan">Rahim Yar Khan</option>
														<option value="Rawalakot">Rawalakot</option>
														<option value="Rajanpur">Rajanpur</option>
														<option value="Sadiqabad">Sadiqabad</option>
														<option value="Sahiwal">Sahiwal</option>
														<option value="Sargodha">Sargodha</option>
														<option value="Sawabi">Sawabi</option>
														<option value="Shakargarh">Shakargarh</option>
														<option value="Sheikhupura">Sheikhupura</option>
														<option value="Sialkot">Sialkot</option>
														<option value="Skardu">Skardu</option>
														<option value="Sukkur">Sukkur</option>
														<option value="Swat">Swat</option>
														<option value="Taxila">Taxila</option>
														<option value="Thatta">Thatta</option>
														<option value="Tibba Sultan Pur">Tibba Sultan Pur</option>
														<option value="Toba Tek Singh">Toba Tek Singh</option>
														<option value="Tunsa">Tunsa</option>
														<option value="Vehari">Vehari</option>
														<option value="Wah">Wah</option>
														<option value="Wazirabad">Wazirabad</option>
														<option value="Ziarat">Ziarat</option>
													</select>
												</div>
											</div>
											<div class="row">
												<div class="card-action">
													<input type="Submit" name="" class="btn btn-success" value="Submit">
													
													<input type="reset" class="btn btn-danger" value="Reset">
												</div>
											</div>
										</form>
									</div>
									
								</div>
							</div>
						
							<div class="col-md-6">
								<div class="card">
									<div class="card-header">
										<div class="card-title">Projects List</div>
									</div>
									<div class="card-body">
										<table class="table table-striped mt-3 datatablejs">
											<thead>
												<tr>
													<th scope="col">S.No</th>
													<th scope="col">Project Name</th>
													<th scope="col">Action</th>
												</tr>
											</thead>
											<tbody>
												@foreach($propertyProjects as $propertyProject)
												<tr>
													<td>{{$loop->iteration}}</td>
													<td>{{$propertyProject->project_name}} {{$propertyProject->project_city}}</td>
													<td>
														<a href="{{ route('propertyproject.edit',$propertyProject->id) }}" class="btn btn-info btn-xs">Edit</a>
														<a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-danger btn-xs">Delete</a>
														<form onsubmit="return confirm('Do you really want to delete?');" action="{{ route('propertyproject.destroy',$propertyProject->id) }}" method="post">
															@method('DELETE')
															<input type="hidden" name="_token" value="{{ csrf_token() }}">
														</form>
													</td>
												</tr>
												@endforeach
											</tbody>
										</table>
									</div>
								</div>
							</div>
						</div>
				</div>
			</div>
			@include('partials.footer')
		</div>
		@include ('partials.js-libraries')
	</div>
</body>
</html>