routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

//---------------------------------------------------------------Property Routes
Route::resource('property', 'PropertyController');
Route::resource('propertyproject','PropertyProjectController');
Route::resource('propertytransactions','PropertyTransactionController');
Route::resource('propertyfiles', 'PropertyFileController');

Route::get('/propertytransactions/create/{id}', 'PropertyTransactionController@create')->name('propertytransactions.create');
Route::resource('propertyexpenses','PropertyExpenseController');
Route::get('/propertyexpenses/create/{id}', 'PropertyExpenseController@create')->name('propertyexpenses.create');
Route::post('/propertyfiles/sale/{id}', 'PropertyFileController@create')->name('propertyfiles.sale');
//Lenders Routes
Route::resource('lenders','LendersController');
//Office Banks and Bank Transaction Routes
Route::resource('banks','OfficeBanksController');
Route::resource('bank_transaction','BankTransactionsController');
//Route::get('/transactions','BankTransactionsController@bankTransactionsDatewise')->name('transactionsdatewise');
//Route::view('/welcome', 'pdashboard');
//----------------------------------------------------------------Emplooyees Routes
Route::resource('payslips', 'EmpSalarySlipsController');	
Route::resource('employees', 'EmployeesController');
Route::resource('advsalarys', 'AdvsalarysrecsController');

//Files Route
Route::get('/file/profit', 'FilesController@profit');
Route::get('/file/sale', 'FilesController@sale');
Route::get('/file/createfilesale/{id}', 'FilesController@createfilesale');
Route::get('/file/showfilesale/{id}', 'FilesController@showfilesale')->name('file.showfilesale');
Route::get('/file/editfilesale/{id}', 'FilesController@editfilesale');
Route::post('/file/updatefilesale/{id}', 'FilesController@updatefilesale');
Route::post('/file/filesale/{id}', 'FilesController@filesale');
//related to file purchase
Route::resource('file', 'FilesController');
//related to file transaction
Route::resource('filetransaction','FilePurchaseTransactionController');
//passing parameter to file transaction create method in controller
Route::get('filetransaction/create/{id}', 'FilePurchaseTransactionController@create')->name('filetransaction.create');
//file sale trnasaction
Route::resource('filesaletransaction','FileSaleTransactionController');
//passing parameter to file transaction create method in controller
Route::get('filesaletransaction/create/{id}', 'FileSaleTransactionController@create')->name('filesaletransaction.create');
//file purchase history when click on 'view purchase history' button
Route::get('/file/showfilehistory/{id}', 'FilesController@showfilehistory');
//for print
Route::get('/file/printfilehistory/{id}', 'FilesController@print');

//for office expenditure
Route::resource('officeexpenditure', 'OfficeExpenditureController');
Route::get('/deposit', 'OfficeExpenditureController@deposit')->name('officeexpenditure');
Route::post('/addofficedeposit', 'OfficeExpenditureController@addofficedeposit');
Route::post('/deleteofficedeposit/{id}', 'OfficeExpenditureController@deleteofficedeposit');
Route::get('/monthlyreport', 'OfficeExpenditureController@monthlyreport');
Route::post('/checkmonthlyexpenses', 'OfficeExpenditureController@checkmonthlyexpenses');
Route::post('/checkmonthlydeposit', 'OfficeExpenditureController@checkmonthlydeposit');

app/Http/Controllers/BankTransactionsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\BankTransaction;
use App\OfficeBank;
use Sessions;


class BankTransactionsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $total_credit = null;
        $total_debit = null;
        $starting_balance = null;
        $balance = null;
        $from = null;
        $to = null;
        $bank_id = $request->input('id');
        $from = $request->input('from');
        $to = $request->input('to');
        if (empty($from) && empty($to))
        {
            $transactions = BankTransaction::where('bank_account_id', $bank_id)->get();
            $total_credit = BankTransaction::select('trans_type', 'trans_amount')->where('trans_type','=', 'Credit')->where('bank_account_id', $bank_id)->sum('trans_amount');
            $total_debit = BankTransaction::select('trans_type', 'trans_amount')->where('trans_type','=', 'Debit')->where('bank_account_id', $bank_id)->sum('trans_amount');
            $starting_balance = Officebank::select('starting_balance')->where('id', $bank_id)->sum('starting_balance');
            $account_details = Officebank::select('bank_name', 'account_title')->where('id', $bank_id)->get();
            $balance =$starting_balance+$total_credit-$total_debit;
            $w_h_tax = BankTransaction::where('bank_account_id', $bank_id)->sum('w_h_tax');
            //dd($total_credit,$total_debit,$starting_balance,$balance);
            //dd($transactions);
            //dd($w_h_tax);
            $bank_accounts = OfficeBank::all();
            return view('finance.bank_transactions.index', compact('transactions', 'bank_accounts', 'starting_balance', 'total_credit','total_debit', 'balance', 'account_details', 'from', 'to', 'w_h_tax'));
        }
        elseif (!empty($from) && !empty($to))
        {
            $transactions = BankTransaction::where('bank_account_id', $bank_id)->whereBetween('trans_date', [$from, $to])->get();
            $total_credit = BankTransaction::select('trans_type', 'trans_amount')->where('trans_type','=', 'Credit')->where('bank_account_id', $bank_id)->whereBetween('trans_date', [$from, $to])->sum('trans_amount');
            $total_debit = BankTransaction::select('trans_type', 'trans_amount')->where('trans_type','=', 'Debit')->where('bank_account_id', $bank_id)->whereBetween('trans_date', [$from, $to])->sum('trans_amount');
            $starting_balance = Officebank::select('starting_balance')->where('id', $bank_id)->sum('starting_balance');
            $account_details = Officebank::select('bank_name', 'account_title')->where('id', $bank_id)->get();
            $w_h_tax = BankTransaction::where('bank_account_id', $bank_id)->whereBetween('trans_date', [$from, $to])->sum('w_h_tax');
            $balance =$starting_balance+$total_credit-$total_debit;
            //dd($from_date,$to_date,$total_credit,$total_debit, $balance);
            //dd($total_credit,$total_debit);
            //dd($total_credit,$total_debit,$starting_balance,$balance);
            //dd($transactions);
            //dd($account_details);
            //dd($w_h_tax);
            $bank_accounts = OfficeBank::all();
            return view('finance.bank_transactions.index', compact('transactions', 'bank_accounts', 'starting_balance', 'total_credit','total_debit', 'balance', 'account_details', 'from', 'to', 'w_h_tax'));
        }
        
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $officebank = OfficeBank::all();
        //dd($officebank);
        return view('finance.bank_transactions.create', compact('officebank'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, BankTransaction $banktransactions)
    {   
        $banktransactions->bank_account_id = $request->bank_account_id;;
        $banktransactions->trans_amount = $request->trans_amount;
        $banktransactions->trans_date = $request->trans_date;
        $banktransactions->trans_type = $request->trans_type;
        $banktransactions->payment_method = $request->payment_method;
        $banktransactions->trans_descp = $request->trans_descp;
        $banktransactions->w_h_tax = $request->w_h_tax;
        $banktransactions->bank_charges = $request->bank_charges;
        $banktransactions->cheque_no = $request->cheque_no;

        $banktransactions->save();
        return redirect()->route('bank_transaction.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        $transaction = BankTransaction::where('id',$id)->get();
        $officebank = OfficeBank::all();
        return view('finance.bank_transactions.show', compact('transaction', 'officebank'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //dd($id);
        $transaction = BankTransaction::find($id);
        $account_id = BankTransaction::select('bank_account_id')->where('id', $id)->get();
        //dd($account_id);
        $banks = OfficeBank::all();
        //dd($transaction,$banks);
        
        return view('finance.bank_transactions.edit', compact('transaction', 'banks', 'account_id'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $banktransactions = BankTransaction::findOrFail($id);
        $banktransactions->bank_account_id = $request->bank_account_id;
        $banktransactions->trans_amount = $request->trans_amount;
        $banktransactions->trans_date = $request->trans_date;
        $banktransactions->trans_type = $request->trans_type;
        $banktransactions->payment_method = $request->payment_method;
        $banktransactions->trans_descp = $request->trans_descp;
        $banktransactions->w_h_tax = $request->w_h_tax;
        $banktransactions->bank_charges = $request->bank_charges;
        $banktransactions->cheque_no = $request->cheque_no;
        $banktransactions->save();
        return redirect()->route('bank_transaction.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        BankTransaction::destroy($id);
        return redirect()->route('bank_transaction.index');
    }
}

resources/views/finance/bank_transactions/create.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>{{ config('app.name', 'Laravel') }}</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">		   						
					<h4 class="page-title">Bank Transactions</h4>
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title">Add Transaction</div>
								</div>
								<div class="card-body">
									<form method="post" action="{{ route('bank_transaction.store') }}">
										<input type="hidden" name="_token" value="{{ csrf_token() }}">
										<div class="row">
											<div class="form-group col-md-4">
												<label for="Account Select">Bank Account</label>
												<select id="bank_selection" class="form-control input-solid" required="">
													<option value="">Select Bank</option>
													@foreach($officebank as $ob)
													<option value="{{ $ob->id }}-{{$ob->taxpayer_status}}">
														{{ $ob->bank_name }}-{{ $ob->account_title }}
													</option>
													@endforeach
												</select>
												<input type="hidden" name="bank_account_id" id="bank_id">
												<input type="hidden" id="taxpayer_status">
											</div>
											<div class="form-group col-md-4">
												<label for="Type Select">Transaction Type</label>
												<select id="type_selection" class="form-control input-solid" name="trans_type" required="">
													<option value="">Select Type</option>
													<option value="Debit">Debit</option>
													<option value="Credit">Credit</option>
												</select>
											</div>
											<div class="form-group col-md-4">
												<label for="Method Select">Payment Method</label>
												<select id="method_selection" class="form-control input-solid" name="payment_method" required="">
													<option value="">Select Method</option>
													<option value="Cash">Cash</option>
													<option value="Cheque">Cheque</option>
												</select>
											</div>
										</div>
										<div class="row">
											<div class="form-group col-md-4">
												<label for="Account">Transaction Amount</label>
												<input type="textbox" class="form-control" id="amount" name="trans_amount" placeholder="Enter Amount">
											</div>
											<div class="form-group col-md-3" id="cheque" style="display: none;">
												<label for="Account">Cheque No</label>
												<input type="textbox" class="form-control" name="cheque_no" placeholder="Cheque No">
											</div>
											<div class="form-group col-md-3" id="debit" style="display: none;">
												<label for="Account">With Holding Tax</label>
												<input type="textbox" class="form-control" id="w_h_tax" name="w_h_tax" placeholder="Total Tax" readonly="">
											</div>
											<div class="form-group col-md-3" id="credit" style="display: none;">
												<label for="Account">Bank Charges</label>
												<input type="textbox" class="form-control" name="bank_charges" placeholder="Bank Charges">
											</div>
											<div class="form-group col-md-4">
												<label for="Transaction Descp">Transaction Description</label>
												<textarea placeholder="Enter Description" class="validate[required] form-control" name="trans_descp" cols="10" rows="2"></textarea>
											</div>
											<div class="form-group col-md-4">
												<label for="Account">Transaction Date</label>
												<input type="date" class="form-control" name="trans_date">
											</div>	
										</div>
										<div class="card-action row justify-content-md-center">
											<div class="col-md-auto">
												<input type="Submit" name="" class="btn btn-success" value="Submit">
												<input type="reset" class="btn btn-danger" value="Cancel">
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>	
					</div>
				</div>
			</div>
			@include('partials.footer')
		</div>
		@include ('partials.js-libraries')
	</div>
</body>
</html>

resources/views/finance/bank_transactions/edit.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>{{ config('app.name', 'Laravel') }}</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">		   						
					<h4 class="page-title">Update Bank Transactions</h4>
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title">Update Transaction on Account
										@foreach($account_id as $bank_id)
											@foreach($banks as $bank)
												@if($bank_id->bank_account_id == $bank->id)
                                        			<b>["{{ $bank->account_title }}"]</b>
                                        		@endif
                                        	@endforeach
                                        @endforeach
									</div>	
								</div>
								<div class="card-body">
									<form method="post" action="{{ route('bank_transaction.update', $transaction->id) }}">
										@method('PUT')
										<input type="hidden" name="_token" value="{{ csrf_token() }}">
										<div class="row">
											<div class="form-group col-md-4">
												<label for="Account Select">Bank Account</label>
												<select id="bank_selection" class="form-control input-solid" required="">
													<option value="">Select Bank</option>
													@foreach($banks as $bank)
													<option value="{{ $bank->id }}-{{$bank->taxpayer_status}}">
														{{ $bank->bank_name }}-{{ $bank->account_title }}
													</option>
													@endforeach
												</select>
												<input type="hidden" name="bank_account_id" id="bank_id">
												<input type="hidden" id="taxpayer_status">
											</div>										
											<div class="form-group col-md-4">
												<label for="Type Select">Transaction Type</label>
												<select id="type_selection" class="form-control input-solid" name="trans_type" required="">
													<option value="">Select Type</option>
													<option value="Debit">Debit</option>
													<option value="Credit">Credit</option>
												</select>
											</div>
											<div class="form-group col-md-4">
												<label for="Method Select">Payment Method</label>
												<select id="method_selection" class="form-control input-solid" name="payment_method" required="">
													<option value="">Select Method</option>
													<option value="Cash">Cash</option>
													<option value="Cheque">Cheque</option>
												</select>
											</div>
										</div>
										<div class="row">
											<div class="form-group col-md-4">
												<label for="Account">Transaction Amount</label>
												<input type="textbox" class="form-control" id="amount" name="trans_amount" value="{{ $transaction->trans_amount }}" placeholder="Enter Amount">
											</div>
											<div class="form-group col-md-3" id="cheque" style="display: none;">
												<label for="Account">Cheque No</label>
												<input type="textbox" class="form-control" name="cheque_no" value="{{ $transaction->cheque_no}}" placeholder="Cheque No">
											</div>
											<div class="form-group col-md-3" id="debit">
												<label for="Account">With Holding Tax</label>
												<input type="textbox" class="form-control" id="w_h_tax" name="w_h_tax" value="{{ $transaction->w_h_tax }}"placeholder="Total Tax" readonly="">
											</div>
											<div class="form-group col-md-3" id="credit">
												<label for="Account">Bank Charges</label>
												<input type="textbox" class="form-control" name="bank_charges" value="{{ $transaction->bank_charges }}" placeholder="Bank Charges">
											</div>
											<div class="form-group col-md-4">
												<label for="Bank Name">Transaction Description</label>
												<textarea type="textbox" class="form-control" cols="10" rows="2" name="trans_descp">
													{{ $transaction->trans_descp }}
												</textarea>
											</div>	
											<div class="form-group col-md-4">
												<label for="Account">Transaction Date</label>
												<input type="date" class="form-control" value="{{ $transaction->trans_date}}" name="trans_date">
											</div>	
										</div>
										<div class="card-action row justify-content-md-center"">
											<div class="col-md-auto">
												<input type="Submit" name="" class="btn btn-success" value="Update Transaction">
											</div>
										</div>
									</form>		
								</div>
							</div>
						</div>	
					</div>
				</div>
			</div>
			@include('partials.footer')
		</div>
		@include ('partials.js-libraries')
	</div>
</body>
</html>

resources/views/finance/bank_transactions/index.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>Kashaf-Enterprises</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">
					<h4 class="page-title">Bank Transaction History</h4>
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title">Select Bank Account or Bank Account and Date:</div>
								</div>
								<div class="card-body">
									<form id="formvalidation" method="GET" action="{{ route('bank_transaction.index') }}">	
										<input type="hidden" name="_token" value="{{ csrf_token() }}">
										<div class="row">
											<div class="form-group col-md-4">
												<label for="Account Select">Bank Account</label>
												<select id="bank_selection" name="id" class="form-control input-solid" required="">
													<option value="">Select Bank Account</option>
													@foreach($bank_accounts as $bank)
													<option value="{{ $bank->id }}">
														{{ $bank->bank_name }}-{{ $bank->account_title }}
													</option>
													@endforeach
												</select>
											</div>
											<div class="form-group col-md-3">
												<label for="Account Select">From Date</label>
												<input type="date" class="form-control" name="from">
											</div>
											<div class="form-group col-md-3">
												<label for="Account Select">To Date</label>
												<input type="date" class="form-control" name="to">
											</div>
										</div>
										<div class="card-action row justify-content-md-center"">
											<div class="col-md-auto">
												<input type="Submit" class="btn btn-warning" value="Submit">
												<input type="reset" class="btn btn-danger" value="Cancel">
											</div>
											<div class="col-md-1" style="margin-top: -15px;">
												<a href="{{ route('bank_transaction.create') }}" style="margin-left: 177px;" class="btn btn-primary text-left mt-3 mb-3"><i class="la la-plus"></i> Add New Transaction</a>
											</div>
										</div>
									</form>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header">
									<div class="row">
										<div class="col-md-auto" style="margin-top: 15px;">
											@foreach($account_details as $account)
											<button class="btn btn-info" value="" readonly="">
												Account = {{ $account->bank_name }} - {{ $account->account_title }}
											</button>
											@endforeach
										</div>
										<div class="col-md-3" style="margin-top: 15px;">
											@foreach($account_details as $account)
											@if(empty($from) && empty($to))
											@else
											<button class="btn btn-default" value="" readonly="">
												Date = {{ date('d M Y', strtotime($from)) }} to {{ date('d M Y', strtotime($to)) }}
											</button>
											@endif
											@endforeach
										</div>
										@if(!empty($w_h_tax))
										<div class="col-md-auto" style="margin-top: 15px; margin-left: 52px;">
											<button class="btn btn-danger" value="" readonly="">Total W-H-Tax = {{ $w_h_tax}}
											</button>
										</div>
										@endif
									</div>
									<div class="row">
										<div class="form-group col-md-3">
											<input type="text" class="btn btn-warning" value="Starting Bal = {{ $starting_balance }}" readonly="">
										</div>
										<div class="form-group col-md-3">
											<input type="text" class="btn btn-success" value="Total Credit = {{ $total_credit }}" readonly="">
										</div>
										<div class="form-group col-md-3">
											<input type="text" class="btn btn-danger" value="Total Debit = {{ $total_debit }}" readonly="">
										</div>
										<div class="form-group col-md-2.5">
											<input type="text" class="btn btn-primary" value="Balance = {{ $balance }}" readonly="">
										</div>
									</div>
								</div>
								<div class="card-body">
									<table class="table table-striped mt-3 datatablejs">
										<thead>
											<tr>
												<th scope="col">S.No</th>
												<th scope="col">Description</th>
												<th scope="col">Amount</th>
												<th scope="col">Type</th>
												<th scope="col">Date</th>
												<th scope="col">Actions</th>
											</tr>
										</thead>
										<tbody>
											@foreach($transactions as $transaction)
											<tr>
												<td>{{$loop->iteration}}</td>
												<td>{{$transaction->trans_descp}}</td>
												<td>{{$transaction->trans_amount}}</td>
												<td>{{$transaction->trans_type}}</td>
												<td>{{ date('d M Y', strtotime($transaction->trans_date)) }}</td>
												<td>
													<a href="{{ route('bank_transaction.show',$transaction->id) }}" class="btn btn-success btn-xs">View</a>	
													<a href="{{ route('bank_transaction.edit',$transaction->id) }}" class="btn btn-info btn-xs">Edit</a>	
													<a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()" class="btn btn-danger btn-xs">Delete</a>
													<form onsubmit="return confirm('Do you really want to delete?');" action="{{ route('bank_transaction.destroy',$transaction->id) }}" method="post">
														@method('DELETE')
														<input type="hidden" name="_token" value="{{ csrf_token() }}">
													</form>
												</td>
											</tr>
											@endforeach
										</tbody>
									</table>					
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		@include('partials.footer')
	</div>
	@include ('partials.js-libraries')
</div>
</body>
</html>

resources/views/finance/bank_transactions/show.blade.php
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
	<title>{{ config('app.name', 'Laravel') }}</title>
	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
	@include('partials.head')
</head>
<body>
	<div class="wrapper">
		@include('partials.header')
		@include('partials.sidebar-menu')
		<div class="main-panel">
			<div class="content">
				<div class="container-fluid">		   						
					<h4 class="page-title">View Bank Transactions</h4>
					<div class="row">
						<div class="col-md-12">
							<div class="card">
								<div class="card-header">
									<div class="card-title">Transaction Details</div>
								</div>
								<div class="card-body">	
									@foreach($transaction as $trans)	
											<div class="row">
												@foreach($officebank as $bank)
													@if($trans->bank_account_id == $bank->id)
												<div class="form-group col-md-4">
													<label for="Account Select">Bank Account</label>
													<select id="bank_selection" class="form-control input-solid" disabled="">
														<option value="">{{ $bank->bank_name }}-{{ $bank->account_title }}</option>
													</select>
												</div>
													@endif
												@endforeach
												<div class="form-group col-md-4">
													<label for="Type Select">Transaction Type</label>
													<select id="type_selection" class="form-control input-solid" name="trans_type" disabled="">
														<option value="">{{ $trans->trans_type }}</option>
													</select>
												</div>
												<div class="form-group col-md-4">
													<label for="Method Select">Payment Method</label>
													<select id="method_selection" class="form-control input-solid" name="payment_method" disabled="">
														<option value="">{{ $trans->payment_method }}</option>
													</select>
												</div>
											</div>
											<div class="row">
												<div class="form-group col-md-4">
													<label for="Account">Transaction Amount</label>
													<input type="textbox" class="form-control" name="trans_amount" value="{{ $trans->trans_amount}}"disabled="">
												</div>
												<div class="form-group col-md-3" id="cheque" >
													<label for="Account">Cheque No</label>
													@if(isset($trans->cheque_no))
													<input type="textbox" class="form-control" name="cheque_no" value="{{ $trans->cheque_no}}" disabled="">
													@else
													<input type="textbox" class="form-control" name="cheque_no" value="N/A" disabled="">
													@endif
												</div>
												<div class="form-group col-md-3" id="debit">
													<label for="Account">With Holding Tax</label>
													@if(isset($trans->w_h_tax))
														<input type="textbox" class="form-control" name="w_h_tax" value="{{ $trans->w_h_tax }}" disabled="">
													@else
														<input type="textbox" class="form-control" name="w_h_tax" value="N/A" disabled="">
													@endif
												</div>
												<div class="form-group col-md-3" id="credit" >
													<label for="Account">Bank Charges</label>
													@if(isset($trans->bank_charges))
														<input type="textbox" class="form-control" name="bank_charges" value="{{ $trans->bank_charges}}"disabled="">
													@else
														<input type="textbox" class="form-control" name="bank_charges" value="N/A" disabled="">
													@endif
												</div>
												<div class="form-group col-md-4">
													<label for="Bank Name">Transaction Description</label>
													<textarea type="textbox" class="form-control" cols="10" rows="2" name="trans_descp" disabled="">
														{{ $trans->trans_descp}}
													</textarea>
												</div>
												<div class="form-group col-md-4">
													<label for="Account">Transaction Date</label>
													<input type="date" value="{{ $trans->trans_date}}" class="form-control" name="trans_date" disabled="">
												</div>
											</div>
										<div class="card-action row justify-content-md-center"">
											<div class="col-md-auto">
												<a href="{{ route('bank_transaction.edit',$trans->id) }}" class="btn btn-default">Edit Transaction</a>
											</div>
										</div>		
									@endforeach
								</div>
							</div>
						</div>	
					</div>
				</div>
			</div>
			@include('partials.footer')
		</div>
		@include ('partials.js-libraries')
	</div>
</body>
</html>